version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: pzb_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-pzb}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-pzb}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - appnet

  backend:
    build:
      context: ./backend
    container_name: pzb_backend
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/${POSTGRES_DB:-pzb}
      CORS_ORIGINS: http://localhost:8080
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - appnet

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE: /api
    container_name: pzb_frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
    networks:
      - appnet

volumes:
  pgdata:

networks:
  appnet:
    driver: bridge
